### ISSUE TITLE
Can't init GLEW

### ISSUE THREAD

**Issue by jitcoder** [WebPlatformForEmbedded/node-wpe-webgl#3]
on Raspberry PI (node v8.9.1) I'm getting the following:

(Raspberry PI Zero W)
GL enabled
GPU mem set to 256Mb
```
initializing GLEW
No protocol specified
/home/smirza/zap-dash/node_modules/wpe-webgl/gles2.js:11
    gles2.init(width, height, fullscreen, title);
          ^

RangeError: Can't init GLEW

    at Object.init (/home/smirza/zap-dash/node_modules/wpe-webgl/gles2.js:11:11)
    at Object.<anonymous> (/home/smirza/zap-dash/index.js:7:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

here is the source code (slightly different from readme example)

```
const webgl = require('wpe-webgl');
const process = require('process');


let continueLooping = true;
const options = { width: 1280, height: 720, fullscreen: true };
const gl = webgl.init(options);

const end = (new Date().getTime()) + (10 * 1000);

const render = () => {
  const now = new Date().getTime();

  gl.clearColor(0, 1.0, 1.0, 0.0);

  // Set the viewport
  gl.viewport(0, 0, 640, 480);

  // Clear the color buffer
  gl.clear(gl.COLOR_BUFFER_BIT);

  // Do other GL-related stuff here.

  webgl.nextFrame(true /* Use false to prevent buffer swapping */);
  if (continueLooping) {
    process.nextTick(render);
  }

  if (now > end) {
    process.exit(0);
  }
}

render();
```

**Comment by jitcoder** [comment]
I suspect this is because I'm using VNC Viewer instead of being connected via HDMI. I'm supposed to get a replacement adapter today, I'll try again while being connected to the HDMI and report back.

**Comment by jitcoder** [comment]
I was able to confirm everything is working as expected. The issue was because I was using vnc viewer. Once plugged in directly to the HDMI everything worked.

**Comment by basvanmeurs** [comment]
Thanks for sharing, but I'm still curious. 

It looks like the module misidentified the platform: it tries to use GLFW/GLEW instead of the broadcom drivers. It looks like your Linux distro has glfw libraries installed, is that correct? Were you using Raspbian?

**Comment by jitcoder** [comment]
Correct I was using Raspbian. It does seem to pick up the right drivers once I hooked in the HDMI and tried.
